title = "PenguinEngine"
gitRepoUrl = "https://github.com/PenguinDevs/PenguinEngine"
gitSourceBranch = "main"
projectName = "PenguinEngine"
tagline = "PenguinDevs's reusable code for Roblox"
autoSectionPath = "src"

[[navbar.items]]
href = "https://discord.gg/mhtGUS8"
label = "Discord"
position = "right"

[footer]
copyright = "Copyright © 2025 Jason Yi. Made with Moonwave."

[docusaurus]
onBrokenLinks = "warn"

[home]
enabled = true
includeReadme = true

[[home.features]]
title = "Composable"
description = "Libraries are modular! Modules are designed to compose both with Roblox and each other."

[[home.features]]
title = "Nevermore compatibility"
description = "Largely inspired by Quenty's Nevermore Engine, and is designed to be compatible with it. This monorepo of packages is merely an extension of Nevermore, and is not a replacement. Although, it can still be installed and used standalone from Nevermore."

[[home.features]]
title = "Roblox"
description = "Built specifically for the Roblox platform, with a focus on performance and maintainability."
